<?php
define('ttAccountActivation' , "Attivazione account");
define('ttActive' , "Attivo");
define('ttActivate' , "Attiva");
define('ttAdd' , "Aggiungi");
define('ttAddSelectedStudents' , "Aggiungi studenti selezionati");
define('ttAdministration' , "Amministrazione");
define('ttAdministrator' , "Amministratore");
define('ttAdminWelcome' , "Benvenuto nel pannello d'amministrazione<br/>Il sistema include:");
define('ttAlias' , "Codice ISO 639-1");
define('ttAndExit' , "ed Esci");
define('ttAnswer' , "Risposta");
define('ttAnswers' , "Risposte");
define('ttArchive' , "Archivia");
define('ttArchived' , "Archiviato");
define('ttAssignSubject' , "Assegna Materia");
define('ttAutomatic' , "Automatico");
define('ttBasedOn' , "Basato su");
define('ttBlocked' , "Bloccato");
define('ttBlock' , "Blocca");
define('ttUnblock' , "Sblocca");
define('ttBonus' , "Bonus");
define('ttCancel' , "Annulla");
define('ttChangeLanguage' , "Cambia lingua");
define('ttChangeVersion' , "Cambia versione");
define('ttCheck' , "Verifica...");
define('ttClose' , "Chiudi");
define('ttClosed' , "Chiuso");
define('ttCorrect' , "Correggi");
define('ttConfiguration' , "Configurazione");
define('ttConfirm' , "Conferma");
define('ttConfirmEmail' , "Conferma E-mail");
define('ttConfirmPassword' , "Conferma Password");
define('ttCreate' , "Crea");
define('ttCArchiveExam' , "Sei sicuro di voler archiviare l'esame?<br/>Non sarà possibile consegnare ulteriori test e tutte le domande da correggere dei test consegnati totalizzeranno 0 punti.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCBlockTest' , "Sei sicuro di voler bloccare questo test?");
define('ttCChangeStatus' , "Sei sicuro di voler impostare lo stato della domanda a _STATUS_?");
define('ttCConfirmTest' , "Vuoi confermare il punteggio finale?<br/>Questo test verrà archiviato! Continuare?");
define('ttCDeleteAnswer' , "Sei sicuro di voler eliminare questa risposta e le sue traduzioni?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteExam' , "Sei sicuro di voler eliminare questo esame?<br/>Tutti i test in corso, consegnati e archiviati verranno eliminati.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteQuestion' , "Sei sicuro di voler eliminare questa domanda e le sue traduzioni?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteRoom' , "Sei sicuro di voler eliminare questa stanza?<br/>L'operazione non potrà essere annullata!<br/>Continuare?");
define('ttCDeleteSubject' , "Sei sicuro di voler eliminare questa materia?<br/>I seguenti elementi verranno PERMANENTEMENTE eliminati:<br/> - Materia<br/> - Tutti gli argomenti<br/> - Tutte le domande e le risposte con le relative traduzioni<br/> - Tutte le impostazioni d'esame<br/> - Tutti gli esami e i test attivi e archiviati<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteSettings' , "Sei sicuro di voler eliminare queste impostazioni d'esame?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteTopic' , "Sei sicuro di voler eliminare questo argomento?<br/>I seguenti elementi verranno PERMANENTEMENTE eliminati:<br/> - Argomento<br/> - Tutte le domande con le relative traduzioni<br/> - Tutte le risposte con le relative traduzioni<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDiscardEdits' , "Le modifiche verranno perse.<br/>Uscire?");
define('ttCDiscardNew' , "L'elemento creato verrà perso.<br/>Uscire?");
define('ttCRegister' , "Sei sicuro di volerti registrare a questo esame?");
define('ttCRegisterStudents' , "Sei sicuro di voler registrare gli studenti selezionati all'esame?");
define('ttCRenewPassword' , "La password per l'esame verrà aggiornata.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCStartExam' , "Vuoi far partire questo esame?");
define('ttCStartTest' , "Vuoi iniziare l'esame ora?<br/>Ti verrà richiesta la password d'accesso all'esame.");
define('ttCStopExam' , "Vuoi fermare questo esame?");
define('ttCSubmitTest' , "Vuoi consegnare il test?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCTest' , "La password è corretta. Il tuo test è pronto e inizierà dopo il tuo click!");
define('ttCumLaudae' , "e Lode");
define('ttCUnblockTest' , "Sei sicuro di voler sbloccare questo test?");
define('ttCUpdateConfigurations' , "Sei sicuro di voler salvare le nuove configurazioni di sistema?");
define('ttCUpdateLanguage' , "Sei sicuro di voler aggiornare i file di lingua?<br/>L'operazione non potrà essere annullata. Continuare?");
define('ttD1' , "Facile");
define('ttD2' , "Intermedio");
define('ttD3' , "Difficile");
define('ttDatabaseConfiguration' , "Configurazione del database");
define('ttDay' , "Giorno");
define('ttDelete' , "Elimina");
define('ttDescription' , "Descrizione");
define('ttDifficulty' , "Difficoltà");
define('ttDifficultyQuestions' , "Domande per difficoltà");
define('ttDistribution' , "Distribuzione");
define('ttDo' , "Esegui esame");
define('ttDTAnswerInfo' , "Visualizzate _TOTAL_ risposte");
define('ttDTAnswerFiltered' , "(filtrate da _MAX_ risposte totali)");
define('ttDTAnswerEmpty' , "Nessuna risposta da visualizzare");
define('ttDTExamInfo' , "Visualizzati _TOTAL_ esami in corso");
define('ttDTExamFiltered' , "(filtrati da _MAX_ esami in corso totali)");
define('ttDTExamEmpty' , "Nessun esame da visualizzare");
define('ttDTQuestionInfo' , "Visualizzate _TOTAL_ domande");
define('ttDTQuestionFiltered' , "(filtrate da _MAX_ domande totali)");
define('ttDTQuestionEmpty' , "Nessuna domanda da visualizzare");
define('ttDTRegisteredStudentInfo' , "Visualizzati _TOTAL_ studenti registrati");
define('ttDTRegisteredStudentFiltered' , "(filtrati da _MAX_ studenti registrati totali)");
define('ttDTRegisteredStudentEmpty' , "Nessuno studente registrato da visualizzare");
define('ttDTStudentsInfo' , "Visualizzati _TOTAL_ studenti");
define('ttDTStudentsFiltered' , "(filtrati da _MAX_ studenti totali)");
define('ttDTStudentsEmpty' , "Nessuno studente da visualizzare");
define('ttDTTeacherInfo' , "Visualizzati _TOTAL_ docenti");
define('ttDTTeacherFiltered' , "(filtrati da _MAX_ docenti totali)");
define('ttDTTeacherEmpty' , "Nessun docente da visualizzare");
define('ttDTTestInfo' , "Visualizzati _TOTAL_ test");
define('ttDTTestFiltered' , "(filtrati da _MAX_ test totali)");
define('ttDTTestEmpty' , "Nessun test da visualizzare");
define('ttDone' , "Esame completato");
define('ttDuration' , "Durata");
define('ttEdit' , "Modifica");
define('ttEditableScore' , "Voto modificabile");
define('ttError' , "Errore");
define('ttEmail' , "E-mail");
define('ttEnd' , "Fine");
define('ttEverywhere' , "Ovunque");
define('ttExam' , "Esame");
define('ttExams' , "Esami");
define('ttExit' , "Uscita");
define('ttExtra' , "Extra");
define('ttExamsArchive' , "Archivia");
define('ttExamsInProgress' , "Esami in corso");
define('ttEActivationFails' , "Attivazione fallita!");
define('ttEAlreadyRegistered' , "Lo studente è già registrato a questo esame!");
define('ttEAnswerInSet' , "L'operazione non può essere completata. La risposta è usata in alcuni test!");
define('ttEAnswerNotFound' , "Risposta non trovata");
define('ttEAnswers' , "Si è verificato un problema con le risposte.<br/>Contattare il docente o l'amministratore.");
define('ttEDatabase' , "Errore nel database!");
define('ttEDates' , "Date non corrette!");
define('ttEEditRoomAll' , "'All' non pùò essere modificata!");
define('ttEEmailAlreadyRegistered' , "E-mail già registrata!");
define('ttEEmailNotRegistered' , "E-mail non registrata!");
define('ttEEmailNotValid' , "L'email inserita non è valida! Inserisci un'indirizzo email valido");
define('ttEEmailsNotMatch' , "Le due email non corrispondono!");
define('ttEEmptyFields' , "Uno o più campi sono vuoti!");
define('ttEExamArchived' , "L'operazione non può essere completata. L'esame è stato già archiviato!");
define('ttEExamNotFound' , "Esame non trovato!");
define('ttEExamNotStarted' , "Non puoi iniziare il test. L'esame non è ancora stato avviato!");
define('ttEExamStarted' , "L'operazione non può essere completata perché l'esame è già iniziato!");
define('ttEExamWaiting' , "L'operazione non può essere completata perché l'esame non è mai stato avviato!");
define('ttEExamsNotArchivedDeleteTopic' , "L'operazione non può essere completata perché uno o più esami non ancora archiviati contengono domande contenute in questo argomento!");
define('ttEExamsNotArchivedEditTestSettings' , "L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.<br/>Sarà possibile aggiornare unicamente nome e descrizione. Continuare?");
define('ttEExamsNotArchivedDeleteTestSettings' , "L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.");
define('ttEIncorrectField' , "Uno o più campi non sono corretti!");
define('ttELogin' , "E-mail e/o Password non sono corretti!");
define('ttEMainLanguageEmpty' , "La lingua principale della materia non può essere vuota!");
define('ttEMandatoryQuestion' , "Questa è una domanda obbligatoria delle impostazioni d'esame '_TESTSETTING_': non è possibile cancellara o modificarne difficoltà e argomento.");
define('ttENotAuthorized' , "Il tuo client non è autorizzato.<br/>Contatta il docente o l'amministratore.");
define('ttENoStudentsToRegister' , "Nessun studente da registrare all'esame!");
define('ttENoTopicsForSubject' , "Nessun argomento esistente per questa materia!<br/>Prima di creare una nuova domanda occorre aver creato almeno un argomento.");
define('ttEOldPasswordWrong' , "La vecchia password non corrisponde!");
define('ttEPassword' , "Password errata!");
define('ttEPasswordShort' , "La password è troppo breve. Deve avere una lunghezza minima di 8 caratteri!");
define('ttEPasswordsNotMatch' , "Le due password non corrispondono!");
define('ttEQuestAnswPicker' , "Errore durante il recupero di domande e risposte.<br/>Contattare il docente!");
define('ttEQuestionInSet' , "L'operazione non può essere completata. La domanda è usata in alcuni test!");
define('ttEQuestionNotFound' , "Domanda non trovata!");
define('ttEQuestionType' , "Tipo di domanda non corretto!");
define('ttERegFailedQuestions' , "Registrazione fallita: poche domande! Contattare il docente.");
define('ttERoomAllDelete' , "'Tutte' non può essere eliminata!");
define('ttERoomUsed' , "L'operazione non può essere completata. La stanza è usata in alcuni esami!");
define('ttESaveBeforeNew' , "Prima di creare un nuovo elemento salva o cancella quello appena creato.");
define('ttESelectQuestionType' , "Selezionare uno dei tipi di domanda disponibili!");
define('ttESelectSubject' , "Selezionare uno dei propri corsi!");
define('ttESelectTestSettings' , "Selezionare una delle impostazioni d'esame!");
define('ttESetNotFound' , "Set di domande non trovato!");
define('ttETestBlockedSubmitted' , "L'operazione non può essere completata. Questo test è stato bloccato o è stato già consegnato!");
define('ttETestAlreadyArchived' , "L'operazione non può essere completata. Questo test è stato già corretto e archiviato!");
define('ttETestAlreadySubmitted' , "L'operazione non può essere completata. Il test è stato già consegnato o archiviato!");
define('ttETestNotArchived' , "L'operazione non può essere completata. Questo test non è stato archiviato!");
define('ttETestNotFound' , "Test non trovato!");
define('ttETestSettingDeleteQuestion' , "L'operazione non può essere completata perché la domanda è obbligatoria nelle seguenti impostazioni d'esame:");
define('ttETestSettingDeleteTopic' , "L'operazione non può essere completata perché alcune domande di questo argomento sono utilizzate nelle seguenti impostazioni d'esame:");
define('ttETestsNotArchived' , "Alcuni test non sono stati archiviati! Correggere prima tutti i test.");
define('ttETimeExpired' , "Il tempo disponibile è finito!");
define('ttETranslationExists' , "La traduzione nella lingua selezionata è già presente!");
define('ttEUserNotFound' , "Utente non trovato!");
define('ttEValues' , "Alcuni valori non sono corretti!");
define('ttFalse' , "Falso");
define('ttFinalScore' , "Punteggio finale");
define('ttGeneralInformations' , "Informazioni Generali");
define('ttHours' , "ore");
define('ttHome' , "Home");
define('ttHomepage' , "Homepage");
define('ttHost' , "Host");
define('ttHAnswPanel' , "Due click per modificare la risposta selezionata");
define('ttHQuestLanguagesPanel' , "Un click per la traduzione<br/>della domanda selezionata");
define('ttHQuestPanel' , "Un click per selezionare la domanda e vederne l'anteprima, due click per modificare domanda e risposte. Doppio click sulle bandierine per attivare e disattivare le domande nei test");
define('ttHQuestPreviewPanel' , "Le risposte con sfondo arancione non sono tradotte nella lingua richiesta");
define('ttHQuestTopicPanel' , "Un click per filtrare le domande,<br/>doppio per modificare l'argomento");
define('ttInfo' , "Informazioni");
define('ttIPEnd' , "IPv4 Fine");
define('ttIPStart' , "IPv4 Inizio");
define('ttInactive' , "Inattivo");
define('ttJoin' , "Iscriviti");
define('ttLanguage' , "Lingua");
define('ttLanguages' , "Lingue");
define('ttLogin' , "Entra");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Login completato!");
define('ttLogout' , "ESCI");
define('ttMailLostPassword' , "Per impostare una nuova password clicca il link seguente:\n\n_LINK_\n\nSe non hai richiesto il reset della password allora ignora questa email.");
define('ttMailCredentials' , "Ciao _USERNAME_,\nDi seguito sono riportate le tue credenziali di accesso:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_");
define('ttMailNewTeacher' , "Benvenuto in _SYSTEMNAME_.\n\nPer attivare il tuo account clicca il link seguente e imposta la tua password personale:");
define('ttMainLanguage' , "Lingua principale");
define('ttManage' , "Gestisci");
define('ttMandatory' , "Fisse");
define('ttManual' , "Manuale");
define('ttMinutes' , "minuti");
define('ttMyExams' , "I miei esami");
define('ttMySettings' , "Le mie impostazioni");
define('ttMySubjects' , "Seleziona un corso");
define('ttMActivation' , "Password impostata correttamente.<br/>Verrai portato alla tua Homepage");
define('ttMAnswerDeleted' , "Risposta eliminata con successo");
define('ttMConfigurationsUpdated' , "Configurazioni di sistema aggiornate con successo");
define('ttMConfirm' , "Test confermato e archiviato correttamente");
define('ttMUserCreated' , "Creazione completata: ti è stata inviata una e-mail per completare la registrazione.<br/>Controlla anche nella cartella Spam");
define('ttMEdit' , "Modifiche salvate correttamente");
define('ttMExamArchived' , "Esame archiviato con successo");
define('ttMExamDeleted' , "Esame eliminato con successo");
define('ttMExamStarted' , "Esame avviato con successo");
define('ttMExamStopped' , "Esame fermato con successo");
define('ttMLanguageCreated' , "Traduzione creata con successo");
define('ttMLanguageSaved' , "Traduzione salvata con successo");
define('ttMLanguageUpdated' , "Traduzione aggiornata con successo");
define('ttMNewAnswer' , "Risposta creata con successo");
define('ttMNewQuestion' , "Domanda creata con successo");
define('ttMNewRoom' , "Stanza creata con successo");
define('ttMNewSettings' , "Impostazioni d'esame create con successo");
define('ttMNewSubject' , "Materia creata con successo");
define('ttMNewTopic' , "Argomento creato con successo");
define('ttMPasswordRenewed' , "Password d'esame rinnovata con successo");
define('ttMQuestionDeleted' , "Domanda eliminata con successo");
define('ttMRegistration' , "Sei stato correttamente registrato all'esame");
define('ttMResetConfirmed' , "Richiesta completata: ti è stata inviata una e-mail per reimpostare la tua password. Controlla anche nella cartella Spam");
define('ttMRoomDeleted' , "Stanza eliminata con successo");
define('ttMSelectLanguage' , "Seleziona la lingua da gestire");
define('ttMSettingsDeleted' , "Impostazioni d'esame eliminate con successso");
define('ttMStudentsRegistered' , "Studenti registrati con successo all'esame");
define('ttMSubjectDeleted' , "Materia eliminata con successo");
define('ttMSubjectQuestions' , "Per gestire gli argomenti e le domande seleziona il corso");
define('ttMSubjectSettings' , "Per gestire le impostazioni d'esame seleziona il corso");
define('ttMTestBlocked' , "Test bloccato con successo");
define('ttMTestSubmitted' , "Test consegnato con successo");
define('ttMTestUnblocked' , "Test sbloccato con successo");
define('ttMTopicDeleted' , "Argomento eliminato con successo");
define('ttName' , "Nome");
define('ttNegativeScores' , "Punteggi negativi");
define('ttNew' , "Nuovo");
define('ttNext' , "Avanti");
define('ttNewAnswer' , "Nuova risposta");
define('ttNewCredentials' , "Nuove credenziali");
define('ttNewLanguage' , "Nuova lingua");
define('ttNewPassword' , "Nuova password");
define('ttNewQuestion' , "Nuova domanda");
define('ttNewRegistration' , "Nuova registrazione");
define('ttNewRoom' , "Nuova stanza");
define('ttNewTeacher' , "Nuovo docente");
define('ttNewTestSettings' , "Nuove impostazioni");
define('ttNewStudent' , "Nuovo studente");
define('ttNewSubject' , "Nuova materia");
define('ttNewTopic' , "Nuovo argomento");
define('ttNewUser' , "Nuovo utente");
define('ttNo' , "No");
define('ttNoAnswers' , "Nessuna risposta disponibile per questa domanda");
define('ttNoExams' , "Nessun esame disponibile per questa materia");
define('ttNoExamInProgress' , "Nessun esame in corso");
define('ttNoInfo' , "Non ci sono informazioni per questo esame");
define('ttNoQuestions' , "Nessuna domanda disponibile per questo argomento");
define('ttNoRooms' , "Nessuna stanza creata: 'Tutte' è l'unica disponibile");
define('ttNoSettings' , "Nessuna impostazione disponile per questa materia");
define('ttNoSubjects' , "Nessuna materia disponibile");
define('ttNoTestToCorrect' , "Nessun test da correggere");
define('ttNoUserRegistered' , "Nessuno studente registrato a questo esame");
define('ttOldPassword' , "Vecchia Password");
define('ttEssayQuestion' , "Domanda a risposta aperta");
define('ttPassword' , "Password");
define('ttPasswordLost' , "Password persa?");
define('ttPort' , "Porta");
define('ttProfile' , "Profilo");
define('ttQuestion' , "Domanda");
define('ttQuestionPreview' , "Anteprima della domanda");
define('ttQuestions' , "Domande");
define('ttQEc' , "Calcolatrice");
define('ttQEp' , "Tavola Periodica");
define('ttQTMC' , "Risposta singola");
define('ttQTMCDescription' , "In una domanda a risposta singola il partecipante sceglie una singola risposta tra tutte quelle fornite.");
define('ttQTMR' , "Risposta multipla");
define('ttQTMRDescription' , "Una domanda a risposta multipla è simile a quella a Risposta Singola, con la differenza che il partecipante può rispondere scegliendo una o più risposte tra quelle fornite.");
define('ttQTES' , "Risposta aperta");
define('ttQTESDescription' , "Una domanda a risposta aperta permette al partecipante di rispondere inserendo un testo libero senza limiti di caratteri. È possibile usare questo tipo di domanda per chiedere opinioni o suggerimenti riguardo una particolare materia.");
define('ttQTYN' , "Si / No");
define('ttQTYNDescription' , "Una domanda Sì/No è una domanda a risposta singola che chiede al partecipante di rispondere con un \"Sì\" o un \"No\".");
define('ttQTTF' , "Vera / Falso");
define('ttQTTFDescription' , "Una domanda Vero/Falso è una domanda a risposta singola che chiede al partecipante di rispondere con un \"Vero\" o un \"Falso\".");
define('ttRandom' , "Casuali");
define('ttRefresh' , "Aggiorna");
define('ttRegister' , "Registrati");
define('ttRegistrations' , "Registrazione");
define('ttRegEnd' , "Chiusura registrazione");
define('ttRenewPassword' , "Rinnova Password");
define('ttReset' , "Reimposta");
define('ttResetPassword' , "Reimposta Password");
define('ttRole' , "Ruolo");
define('ttRooms' , "Stanze");
define('ttSave' , "Salva");
define('ttSaveAnswerInfo' , "Salva Informazioni Risposta");
define('ttSaveLanguageFiles' , "Salva file di lingua");
define('ttSaveLanguageXML' , "Salva file XML di lingua");
define('ttSaveQuestionInfo' , "Salva Informazioni Domanda");
define('ttScore' , "Punteggio");
define('ttScoreFinal' , "Punteggio finale");
define('ttScoreTest' , "Punteggio del test");
define('ttScoreType' , "Tipo di punteggio");
define('ttScoreMin' , "Punteggio minimo");
define('ttSelectSubject' , "Seleziona un corso");
define('ttSelectSubjectBefore' , "Selezionare prima un corso");
define('ttSet' , "Imposta");
define('ttSetPassword' , "Imposta la tua password");
define('ttShowHide' , "Mostra/Nascondi");
define('ttSkin' , "Skin");
define('ttSettings' , "Impostazioni");
define('ttStart' , "Inizia");
define('ttStarted' , "Iniziato");
define('ttStop' , "Ferma");
define('ttStopped' , "Fermato");
define('ttStartTest' , "Inizia test");
define('ttStatus' , "Stato");
define('ttStats' , "Statistiche");
define('ttStudent' , "Studente");
define('ttStudents' , "Studenti");
define('ttST10' , "Decimi");
define('ttST30' , "Trentesimi");
define('ttST100' , "Centesimi");
define('ttSubject' , "Materia");
define('ttSubjects' , "Materie");
define('ttSubmit' , "Consegna");
define('ttSurname' , "Cognome");
define('ttSystem' , "Sistema");
define('ttSystemConfiguration' , "Configurazione di Sistema");
define('ttTeacher' , "Docente");
define('ttTeachers' , "Docenti");
define('ttTest' , "Test");
define('ttTests' , "Test");
define('ttTestToCorrect' , "Tests da correggere");
define('ttText' , "Testo");
define('ttTime' , "Ora");
define('ttTimeEnd' , "Ora di fine");
define('ttTimeStart' , "Ora di inizio");
define('ttTimeUsed' , "Tempo usato");
define('ttTimeZone' , "Fuso orario");
define('ttTitle' , "Titolo");
define('ttTopic' , "Argomento");
define('ttTopics' , "Argomenti");
define('ttTopicsAndQuestions' , "Argomenti e Domande");
define('ttTopicsQuestions' , "Domande per argomenti");
define('ttTranslations' , "Traduzioni");
define('ttTrue' , "Vero");
define('ttType' , "Tipo");
define('ttUser' , "Utente");
define('ttUsers' , "Utenti");
define('ttView' , "Vedi");
define('ttWelcome' , "Benvenuto");
define('ttWaiting' , "Attesa");
define('ttWarning' , "Attenzione");
define('ttYes' , "Sì");
define('ttImportQM' , "ImportQM");
define('ttImport' , "Import");
