<?php
define('ttAccountActivation' , 'Attivazione account');
define('ttActive' , 'Attivo');
define('ttActivate' , 'Attiva');
define('ttAdd' , 'Aggiungi');
define('ttAddSelectedStudents' , 'Aggiungi studenti selezionati');
define('ttAdministration' , 'Amministrazione');
define('ttAdministrator' , 'Amministratore');
define('ttAdminWelcome' , 'Benvenuto nel pannello d\'amministrazione<br/>Il sistema include:');
define('ttAlias' , 'Codice ISO 639-1');
define('ttAndExit' , ' ed Esci');
define('ttAnswer' , 'Risposta');
define('ttAnswers' , 'Risposte');
define('ttArchive' , 'Archivia');
define('ttArchived' , 'Archiviato');
define('ttAssignSubject' , 'Assegna Materia');
define('ttAutomatic' , 'Automatico');
define('ttBlocked' , 'Bloccato');
define('ttBlock' , 'Blocca');
define('ttUnblock' , 'Sblocca');
define('ttBonus' , 'Bonus');
define('ttCancel' , 'Annulla');
define('ttChangeLanguage' , 'Cambia lingua');
define('ttChangeVersion' , 'Cambia versione');
define('ttClose' , 'Chiudi');
define('ttClosed' , 'Chiuso');
define('ttCorrect' , 'Correggi');
define('ttConfirm' , 'Conferma');
define('ttConfirmEmail' , 'Conferma E-mail');
define('ttConfirmPassword' , 'Conferma Password');
define('ttCreate' , 'Crea');
define('ttD1' , 'Facile');
define('ttD2' , 'Intermedio');
define('ttD3' , 'Difficile');
define('ttDistributionP' , 'Proporzionale');
define('ttDistributionU' , 'Universale');
define('ttDay' , 'Giorno');
define('ttDelete' , 'Elimina');
define('ttDescription' , 'Descrizione');
define('ttDifficulty' , 'Difficoltà');
define('ttDifficultyQuestions', 'Domande per difficoltà');
define('ttDistribution' , 'Distribuzione');
define('ttDo' , 'Esegui esame');
define('ttDone' , 'Esame completato');
define('ttDuration' , 'Durata');
define('ttEdit' , 'Modifica');
define('ttError' , 'Errore');
define('ttEmail' , 'E-mail');
define('ttEnd' , 'Fine');
define('ttEverywhere' , 'Ovunque');
define('ttExam' , 'Esame');
define('ttExams' , 'Esami');
define('ttExit' , 'Uscita');
define('ttExtra' , 'Extra');
define('ttExamsArchive' , 'Archivia');
define('ttExamsInProgress' , 'Esami in corso');
define('ttEActivationFails' , 'Attivazione fallita!');
define('ttEAlreadyRegistered' , 'Lo studente è già registrato a questo esame!');
define('ttEAnswerInSet' , 'L\'operazione non può essere completata. La risposta è usata in alcuni test!');
define('ttEAnswerNotFound' , 'Risposta non trovata');
define('ttEAnswers' , 'Si è verificato un problema con le risposte.<br/>Contattare il docente o l\'amministratore.');
define('ttEDatabase' , 'Errore nel database!');
define('ttEEditRoomAll' , '\'All\' non pùò essere modificata!');
define('ttEEmailAlreadyRegistered' , 'E-mail già registrata!');
define('ttEEmailNotRegistered' , 'E-mail non registrata!');
define('ttEEmptyFields' , 'Uno o più campi sono vuoti!');
define('ttEExamArchived' , 'L\'operazione non può essere completata. L\'esame è stato già archiviato!');
define('ttEExamNotFound' , 'Esame non trovato!');
define('ttEExamNotStarted' , 'Non puoi iniziare il test. L\'esame non è ancora stato avviato!');
define('ttEExamStarted' , 'L\'operazione non può essere completata perché l\'esame è già iniziato!');
define('ttEExamWaiting' , 'L\'operazione non può essere completata perché l\'esame non è mai stato avviato!');
define('ttEExamsNotArchivedDeleteTopic' , 'L\'operazione non può essere completata perché uno o più esami non ancora archiviati contengono domande contenute in questo argomento!');
define('ttEExamsNotArchivedEditTestSettings' , 'L\'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.<br/>Sarà possibile aggiornare unicamente nome e descrizione. Continuare?');
define('ttEExamsNotArchivedDeleteTestSettings' , 'L\'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato!');
define('ttEMainLanguageEmpty' , 'La traduzione principale della materia non può essere vuota!');
define('ttEMandatoryQuestion' , 'Questa è una domanda obbligatoria delle impostazioni d\'esame \'_TESTSETTING_\': non è possibile cancellara o modificarne difficoltà e argomento.');
define('ttENotAuthorized' , 'Il tuo client non è autorizzato.<br/>Contatta il docente o l\'amministratore.');
define('ttEOldPasswordWrong' , 'La vecchia password non corrisponde!');
define('ttEPassword' , 'Password errata!');
define('ttEQuestionInSet' , 'L\'operazione non può essere completata. La domanda è usata in alcuni test!');
define('ttEQuestionNotFound' , 'Domanda non trovata!');
define('ttEQuestionType' , 'Tipo di domanda non corretto!');
define('ttERegFailedQuestions' , 'Registrazione fallita: poche domande! Contattare il docente.');
define('ttERoomAllDelete' , '\'Tutte\' non può essere eliminata!');
define('ttERoomUsed' , 'L\'operazione non può essere completata. La stanza è usata in alcuni esami!');
define('ttESetNotFound' , 'Set di domande non trovato!');
define('ttETestAlreadyArchived' , 'L\'operazione non può essere completata. Questo test è stato già corretto e archiviato!');
define('ttETestAlreadySubmitted' , 'L\'operazione non può essere completata. Il test è stato già consegnato o archiviato!');
define('ttETestBlockedSubmitted' , 'L\'operazione non può essere completata. Questo test è stato bloccato o è stato già consegnato!');
define('ttETestNotArchived' , 'L\'operazione non può essere completata. Questo test non è stato archiviato!');
define('ttETestNotFound' , 'Test non trovato!');
define('ttETestSettingDeleteQuestion' , 'L\'operazione non può essere completata perché la domanda è obbligatoria nelle seguenti impostazioni d\'esame:<br/>');
define('ttETestSettingDeleteTopic' , 'L\'operazione non può essere completata perché alcune domande di questo argomento sono utilizzate nelle seguenti impostazioni d\'esame:<br/>');
define('ttETestsNotArchived' , 'Alcuni test non sono stati archiviati! Correggere prima tutti i test.');
define('ttETimeExpired' , 'Il tempo disponibile è finito!');
define('ttEUserNotFound' , 'Utente non trovato!');
define('ttEValues' , 'Alcuni valori non sono corretti!');
define('ttFalse' , 'Falso');
define('ttFinalScore' , 'Punteggio finale');
define('ttGeneralInformations', 'Informazioni Generali');
define('ttHours' , 'ore');
define('ttInfo' , 'Informazioni');
define('ttIPEnd' , 'IPv4 Fine');
define('ttIPStart' , 'IPv4 Inizio');
define('ttInactive' , 'Inattivo');
define('ttJoin' , 'Iscriviti');
define('ttLanguage' , 'Lingua');
define('ttLanguages' , 'Lingue');
define('ttLogin' , 'Entra');
define('ttLogout' , 'ESCI');
define('ttMailLostPassword' , 'Per impostare una nuova password clicca il link seguente:\n\n_LINK_\n\nSe non hai richiesto il reset della password allora ignora questa email.');
define('ttMailCredentials' , 'Ciao _USERNAME_ ,\nDi seguito sono riportate le tue credenziali di accesso:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_');
define('ttMailNewTeacher' , 'Benvenuto in _SYSTEMNAME_.\n\nPer attivare il tuo account clicca il link seguente e imposta la tua password personale:');
define('ttMainLanguage' , 'Lingua principale');
define('ttManage' , 'Gestisci');
define('ttMandatory', 'Fisse');
define('ttManual' , 'Manuale');
define('ttMinutes' , 'minuti');
define('ttMyExams' , 'I miei esami');
define('ttMySettings' , 'Le mie impostazioni');
define('ttMySubjects' , 'Seleziona un corso');
define('ttMSelectLanguage' , 'Seleziona la lingua da gestire');
define('ttMSubjectQuestions' , 'Per gestire gli argomenti e le domande seleziona il corso');
define('ttMSubjectSettings' , 'Per gestire le impostazioni d\'esame seleziona il corso');
define('ttName' , 'Nome');
define('ttNew' , 'Nuovo');
define('ttNewAnswer' , 'Nuova risposta');
define('ttNewCredentials' , 'Nuove credenziali');
define('ttNewLanguage' , 'Nuova lingua');
define('ttNewPassword' , 'Nuova password');
define('ttNewQuestion' , 'Nuova domanda');
define('ttNewRegistration' , 'Nuova registrazione');
define('ttNewRoom' , 'Nuova stanza');
define('ttNewTeacher' , 'Nuovo docente');
define('ttNewTestSettings' , 'Nuove impostazioni');
define('ttNewStudent' , 'Nuovo studente');
define('ttNewSubject' , 'Nuova materia');
define('ttNewTopic' , 'Nuovo argomento');
define('ttNewUser' , 'Nuovo utente');
define('ttNoAnswers' , 'Nessuna risposta disponibile per questa domanda');
define('ttNoExams' , 'Nessun esame disponibile per questa materia');
define('ttNoExamInProgress' , 'Nessun esame in corso');
define('ttNoInfo' , 'Non ci sono informazioni per questo esame');
define('ttNoQuestions' , 'Nessuna domanda disponibile per questo argomento');
define('ttNoRooms' , 'Nessuna stanza creata: \'Tutte\' è l\'unica disponibile');
define('ttNoSettings' , 'Nessuna impostazione disponile per questa materia');
define('ttNoSubjects' , 'Nessuna materia disponibile');
define('ttNoTestToCorrect' , 'Nessun test da correggere');
define('ttNoUserRegistered' , 'Nessuno studente registrato a questo esame');
define('ttOldPassword' , 'Vecchia Password');
define('ttOpenQuestion' , 'Domanda aperta');
define('ttPassword' , 'Password');
define('ttPasswordLost' , 'Password persa?');
define('ttProfile' , 'Profilo');
define('ttQuestion' , 'Domanda');
define('ttQuestionPreview' , 'Anteprima della domanda');
define('ttQuestions' , 'Domande');
define('ttQEc' , 'Calcolatrice');
define('ttQEp', 'Tavola Periodica');
define('ttQTMC' , 'Risposta singola');
define('ttQTMR' , 'Risposta multipla');
define('ttQTOP' , 'Risposta aperta');
define('ttRandom', 'Casuali');
define('ttRefresh' , 'Aggiorna');
define('ttRegister' , 'Registrati');
define('ttRegistrations' , 'Registrazione');
define('ttRegEnd' , 'Chiusura registrazione');
define('ttRenewPassword' , 'Rinnova Password');
define('ttReset' , 'Reimposta');
define('ttResetPassword' , 'Reimposta Password');
define('ttRole' , 'Ruolo');
define('ttRooms' , 'Stanze');
define('ttSave' , 'Salva');
define('ttSaveAnswerInfo', 'Salva Informazioni Risposta');
define('ttSaveLanguageFiles' , 'Salva file di lingua');
define('ttSaveLanguageXML' , 'Salva file XML di lingua');
define('ttSaveQuestionInfo', 'Salva Informazioni Domanda');
define('ttScore' , 'Punteggio');
define('ttScoreFinal' , 'Voto finale');
define('ttScoreTest' , 'Voto del test');
define('ttScoreType' , 'Tipo di punteggio');
define('ttScoreMin' , 'Punteggio minimo');
define('ttSelectSubject' , 'Seleziona un corso');
define('ttSelectSubjectBefore' , 'Selezionare prima un corso');
define('ttSet' , 'Imposta');
define('ttSetPassword' , 'Imposta la tua password');
define('ttSettings' , 'Impostazioni');
define('ttShowHide' , 'Mostra/Nascondi');
define('ttStart' , 'Inizia');
define('ttStarted' , 'Iniziato');
define('ttStartTest' , 'Inizia test');
define('ttStatus' , 'Stato');
define('ttStats' , 'Statistiche');
define('ttStop' , 'Ferma');
define('ttStopped' , 'Fermato');
define('ttStudent' , 'Studente');
define('ttStudents' , 'Studenti');
define('ttST10' , 'Decimi');
define('ttST30' , 'Trentesimi');
define('ttST100' , 'Centesimi');
define('ttSubject' , 'Materia');
define('ttSubjects' , 'Materie');
define('ttSubmit' , 'Consegna');
define('ttSurname' , 'Cognome');
define('ttSystem' , 'Sistema');
define('ttTeacher' , 'Docente');
define('ttTeachers' , 'Docenti');
define('ttTest' , 'Test');
define('ttTests' , 'Test');
define('ttTestToCorrect' , 'Tests da correggere');
define('ttText' , 'Testo');
define('ttTime' , 'Ora');
define('ttTimeEnd' , 'Ora di fine');
define('ttTimeStart' , 'Ora di inizio');
define('ttTimeUsed' , 'Tempo usato');
define('ttTopic' , 'Argomento');
define('ttTopics' , 'Argomenti');
define('ttTopicsAndQuestions' , 'Argomenti e Domande');
define('ttTopicsQuestions', 'Domande per argomento');
define('ttTranslations' , 'Traduzioni');
define('ttTrue' , 'Vero');
define('ttType' , 'Tipo');
define('ttUsers' , 'Utenti');
define('ttView' , 'Vedi');
define('ttWelcome' , 'Benvenuto');
define('ttWaiting' , 'Attesa');