<?php
define('ttAccountActivation' , 'Account Activation');
define('ttActive' , 'Active');
define('ttActivate' , 'Activate');
define('ttAdd' , 'Add');
define('ttAddSelectedStudents' , 'Add Selected Students');
define('ttAdministration' , 'Administration');
define('ttAdministrator' , 'Administrator');
define('ttAdminWelcome' , 'Welcome to the administation panel.<br/>This system includes:');
define('ttAlias' , 'ISO 639-1 Code');
define('ttAndExit' , ' and Exit');
define('ttAnswer' , 'Answer');
define('ttAnswers' , 'Answers');
define('ttArchive' , 'Archive');
define('ttArchived' , 'Archived');
define('ttAssignSubject' , 'Assign Subject');
define('ttAutomatic' , 'Automatic');
define('ttBlocked' , 'Blocked');
define('ttBlock' , 'Block');
define('ttUnblock' , 'Unblock');
define('ttBonus' , 'Bonus');
define('ttCancel' , 'Cancel');
define('ttChangeLanguage' , 'Change Language');
define('ttChangeVersion' , 'Change Test Version');
define('ttClose' , 'Close');
define('ttClosed' , 'Closed');
define('ttCorrect' , 'Correct');
define('ttConfirm' , 'Confirm');
define('ttConfirmEmail' , 'Confirm Email');
define('ttConfirmPassword' , 'Confirm Password');
define('ttCreate' , 'Create');
define('ttD1' , 'Easy');
define('ttD2' , 'Medium');
define('ttD3' , 'Hard');
define('ttDistributionP' , 'Proportional');
define('ttDistributionU' , 'Universal');
define('ttDay' , 'Day');
define('ttDelete' , 'Delete');
define('ttDescription' , 'Description');
define('ttDifficulty' , 'Difficulty');
define('ttDifficultyQuestions', 'Questions for Difficulty');
define('ttDistribution' , 'Distribution');
define('ttDo' , 'Do Exam');
define('ttDone' , 'Exam done');
define('ttDuration' , 'Duration');
define('ttEdit' , 'Edit');
define('ttError' , 'Error');
define('ttEmail' , 'E-mail');
define('ttEnd' , 'End');
define('ttEverywhere' , 'Everywhere');
define('ttExam' , 'Exam');
define('ttExams' , 'Exams');
define('ttExit' , 'Exit');
define('ttExtra' , 'Extra');
define('ttExamsArchive' , 'Archive');
define('ttExamsInProgress' , 'Exams in progress');
define('ttEActivationFails' , 'Activation fails!');
define('ttEAlreadyRegistered' , 'The student is already registered for this exam!');
define('ttEAnswerInSet' , 'The operation can not be completed. The answer is used in some tests!');
define('ttEAnswerNotFound' , 'Answer not found');
define('ttEAnswers' , 'A problem with answers occurred.<br/>Please contact the teacher or the admin.');
define('ttEDatabase' , 'Database Error!');
define('ttEEditRoomAll' , '\'All\' room can not be edited!');
define('ttEEmailAlreadyRegistered' , 'E-mail already registered!');
define('ttEEmailNotRegistered' , 'E-mail not registered!');
define('ttEEmptyFields' , 'One or more fields are empty!');
define('ttEExamArchived' , 'The operation can not be completed. The exam has already been archived!');
define('ttEExamNotFound' , 'Exam not found!');
define('ttEExamNotStarted' , 'You can not start the exam. It is not active yet!');
define('ttEExamStarted' , 'The operation can not be completed because the exam is already started!');
define('ttEExamWaiting' , 'The operation can not be completed because the exam is never started!');
define('ttEExamsNotArchivedDeleteTopic' , 'The operation can not be completed, because at least one not archived exam contains questions from this topic!');
define('ttEExamsNotArchivedEditTestSettings' , 'The operation can not be completed, because these settings are used by at least one not archived exam.<br/>Only name and description will be updated. Continue?');
define('ttEExamsNotArchivedDeleteTestSettings' , 'The operation can not be completed, because these settings are used by at least one not archived exam!');
define('ttEMainLanguageEmpty' , 'Subject\'s main translation can not be empty!');
define('ttEMandatoryQuestion' , 'This is a mandatory question of \'_TESTSETTING_\' test\'s setting: you can\'t delete it or edit its difficulty or topic.');
define('ttENotAuthorized' , 'Your client is not authorized.<br/>Please contact the teacher or the admin.');
define('ttEOldPasswordWrong' , 'The old password is not correct!');
define('ttEPassword' , 'Wrong password!');
define('ttEQuestionInSet' , 'The operation can not be completed. The question is used some tests!');
define('ttEQuestionNotFound' , 'Question not found!');
define('ttEQuestionType' , 'Question type not correct!');
define('ttERegFailedQuestions' , 'Registration failed: too few questions! Please contact the teacher.');
define('ttERoomAllDelete' , '\'All\' room can not be deleted!');
define('ttERoomUsed' , 'The operation can not be completed. The room is used in some exams!');
define('ttESetNotFound' , 'Questions set not found!');
define('ttETestAlreadyArchived' , 'The operation can not be completed. This test has already been corrected and archived!');
define('ttETestAlreadySubmitted' , 'The operation can not be completed. This test has already been submitted and/or archived.');
define('ttETestBlockedSubmitted' , 'The operation can not be completed. This test has been blocked or has already been submitted!');
define('ttETestNotArchived' , 'The operation can not be completed. This test has not been archived!');
define('ttETestNotFound' , 'Test not found!');
define('ttETestsNotArchived' , 'Some tests have not been archived! Please correct all the tests before.');
define('ttETestSettingDeleteQuestion' , 'The operation can not be completed. This question is mandatory in the following test\'s settings:<br/>');
define('ttETestSettingDeleteTopic' , 'The operation can not ben completed. Some questions of this topic are used in the following test\'s settings:<br/>');
define('ttETimeExpired' , 'The available time is expired!');
define('ttEUserNotFound' , 'User not found!');
define('ttEValues' , 'Some values are not correct!');
define('ttFalse' , 'False');
define('ttFinalScore' , 'Final Score');
define('ttGeneralInformations', 'General Informations');
define('ttHours' , 'hours');
define('ttInfo' , 'Info');
define('ttIPEnd' , 'IPv4 End');
define('ttIPStart' , 'IPv4 Start');
define('ttInactive' , 'Inactive');
define('ttJoin' , 'Join');
define('ttLanguage' , 'Language');
define('ttLanguages' , 'Languages');
define('ttLogin' , 'Login');
define('ttLogout' , 'LOGOUT');
define('ttMailLostPassword' , 'To reset your account password please click the following link:\n\n_LINK_\n\nIf you have not request a password reset ignore this email.');
define('ttMailCredentials' , 'Hi _USERNAME_,\nBelow are shown your personal access credentials:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_');
define('ttMailNewTeacher' , 'Welcome to _SYSTEMNAME_.\n\nTo activate your accunt please click the following link and set your personal account\'s password:');
define('ttMainLanguage' , 'Main Language');
define('ttManage' , 'Manage');
define('ttMandatory', 'Mandatory');
define('ttManual' , 'Manual');
define('ttMinutes' , 'minutes');
define('ttMyExams' , 'My Exams');
define('ttMySettings' , 'My Settings');
define('ttMySubjects' , 'Select subject');
define('ttMSelectLanguage' , 'Select the language you want manage');
define('ttMSubjectQuestions' , 'To manage topics and questions, plase select the subject');
define('ttMSubjectSettings' , 'To manage exam\'s settings, please select the subject');
define('ttName' , 'Name');
define('ttNew' , 'New');
define('ttNewAnswer' , 'New Answer');
define('ttNewCredentials' , 'New Credentials');
define('ttNewLanguage' , 'New Language');
define('ttNewPassword' , 'New Password');
define('ttNewQuestion' , 'New Question');
define('ttNewRegistration' , 'New Registration');
define('ttNewRoom' , 'New Room');
define('ttNewTeacher' , 'New Teacher');
define('ttNewTestSettings' , 'New Settings');
define('ttNewSubject' , 'New Subject');
define('ttNewStudent' , 'New Student');
define('ttNewTopic' , 'New Topic');
define('ttNewUser' , 'New User');
define('ttNoAnswers' , 'No answers available for this question');
define('ttNoExams' , 'No exams available for this subject');
define('ttNoExamInProgress' , 'No exam in progress');
define('ttNoInfo' , 'There aren\'t informations about this exam');
define('ttNoQuestions' , 'No questions available for this topic');
define('ttNoRooms' , 'No rooms created: \'All\' only available');
define('ttNoSettings' , 'No settings available for this subject');
define('ttNoSubjects' , 'No subjects available');
define('ttNoTestToCorrect' , 'No tests to correct');
define('ttNoUserRegistered' , 'No registered users for this exam');
define('ttOldPassword' , 'Old Password');
define('ttOpenQuestion' , 'Open question');
define('ttPassword' , 'Password');
define('ttPasswordLost' , 'Password Lost?');
define('ttProfile' , 'Profile');
define('ttQuestion' , 'Question');
define('ttQuestionPreview' , 'Question Preview');
define('ttQuestions' , 'Questions');
define('ttQEc' , 'Calculator');
define('ttQEp' , 'Periodic Table');
define('ttQTMC' , 'Multiple Choice');
define('ttQTMR' , 'Multiple Response');
define('ttQTOP' , 'Open Answer');
define('ttRandom', 'Random');
define('ttRefresh' , 'Refresh');
define('ttRegister' , 'Register');
define('ttRegistrations' , 'Registrations');
define('ttRegEnd' , 'Registration closure');
define('ttRenewPassword' , 'Renew Password');
define('ttReset' , 'Reset');
define('ttResetPassword' , 'Reset Password');
define('ttRole' , 'Role');
define('ttRooms' , 'Rooms');
define('ttSave' , 'Save');
define('ttSaveAnswerInfo', 'Save Answer Info');
define('ttSaveLanguageFiles' , 'Save Language Files');
define('ttSaveLanguageXML' , 'Save XML Language Files');
define('ttSaveQuestionInfo', 'Save Question Info');
define('ttScore' , 'Score');
define('ttScoreFinal' , 'Final Score');
define('ttScoreTest' , 'Test Score');
define('ttScoreType' , 'Score Type');
define('ttScoreMin' , 'Minimum Score');
define('ttSelectSubject' , 'Select Subject');
define('ttSelectSubjectBefore' , 'Select a Subject before');
define('ttSet' , 'Set');
define('ttSetPassword' , 'Please set your password');
define('ttSettings' , 'Settings');
define('ttShowHide' , 'Show/Hide');
define('ttStart' , 'Start');
define('ttStarted' , 'Started');
define('ttStartTest' , 'Start Test');
define('ttStatus' , 'Status');
define('ttStats' , 'Stats');
define('ttStop' , 'Stop');
define('ttStopped' , 'Stopped');
define('ttStudent' , 'Student');
define('ttStudents' , 'Students');
define('ttST10' , 'Tenths');
define('ttST30' , 'Thirtieths');
define('ttST100' , 'Hundredth');
define('ttSubject' , 'Subject');
define('ttSubjects' , 'Subjects');
define('ttSubmit' , 'Submit');
define('ttSurname' , 'Surname');
define('ttSystem' , 'System');
define('ttTeacher' , 'Teacher');
define('ttTeachers' , 'Teachers');
define('ttTest' , 'Test');
define('ttTests' , 'Tests');
define('ttTestToCorrect' , 'Tests to correct');
define('ttText' , 'Text');
define('ttTime' , 'Time');
define('ttTimeEnd' , 'Time End');
define('ttTimeStart' , 'Time Start');
define('ttTimeUsed' , 'Time Used');
define('ttTopic' , 'Topic');
define('ttTopics' , 'Topics');
define('ttTopicsAndQuestions' , 'Topics and Questions');
define('ttTopicsQuestions', 'Questions for Topics');
define('ttTranslations' , 'Translations');
define('ttTrue' , 'True');
define('ttType' , 'Type');
define('ttUsers' , 'Users');
define('ttView' , 'View');
define('ttWelcome' , 'Welcome');
define('ttWaiting' , 'Waiting');